#!/usr/bin/env bun
// Gera src/embed.ts com o driver embutido

import { readdirSync, readFileSync, statSync, writeFileSync } from "fs";
import { join, relative } from "path";

function walk(dir: string, base = dir): Record<string, string> {
  const out: Record<string, string> = {};
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const rel = relative(base, full);
    const st = statSync(full);
    if (st.isDirectory()) {
      Object.assign(out, walk(full, base));
    } else if (st.isFile()) {
      if (full.endsWith(".webp")) continue;
      try {
        out[rel] = readFileSync(full, "utf-8");
      } catch {
        // binary skip
      }
    }
  }
  return out;
}

const vendorFiles = walk("vendor/predator-power-driver");

const code = `// Auto-generated by gen_embed.ts\nexport const VENDOR_FILES: Record<string, string> = ${JSON.stringify(vendorFiles, null, 2)};\n`;

writeFileSync("src/embed.ts", code);
console.log("src/embed.ts OK");
