#!/usr/bin/env bun
// Gera src/embed.ts com o driver embutido

import { readdirSync, readFileSync, statSync, writeFileSync } from "fs";
import { join, relative } from "path";

function shouldSkip(rel: string): boolean {
  const name = rel.split(/[\\/]/).pop() || rel;
  if (rel.split(/[\\/]/).some((part) => part.startsWith("."))) return true;
  if (name === "Module.symvers" || name === "modules.order") return true;
  if (/\.(o|ko|mod|mod\.c|cmd|o\.d)$/.test(name)) return true;
  if (name.endsWith(".webp")) return true;
  return false;
}

function walk(dir: string, base = dir): Record<string, string> {
  const out: Record<string, string> = {};
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const rel = relative(base, full);
    const st = statSync(full);
    if (st.isDirectory()) {
      if (!shouldSkip(rel)) Object.assign(out, walk(full, base));
    } else if (st.isFile()) {
      if (shouldSkip(rel)) continue;
      try {
        out[rel] = readFileSync(full, "utf-8");
      } catch {
        // binary skip
      }
    }
  }
  return out;
}

const vendorFiles = walk("vendor/predator-power-driver");

const code = `// Auto-generated by gen_embed.ts\nexport const VENDOR_FILES: Record<string, string> = ${JSON.stringify(vendorFiles, null, 2)};\n`;

writeFileSync("src/embed.ts", code);
console.log("src/embed.ts OK");
